server.port: 3312

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/foresight
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

