server.port: 3312

spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/foresight
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(L0IEaxNjDvy+Lm6iK3Uxfw==)
    password: ENC(L0IEaxNjDvy+Lm6iK3Uxfw==)

mybatis:
  table:
    auto: update
  model:
    pack: cf.epiphania.foresight
  database:
    type: mysql

mybatis-plus:
  mapper-locations: classpath*:cf/epiphania/foresight/mapper/*.xml,classpath*:com/gitee/sunchenbin/mybatis/actable/mapping/*/*.xml

email:
  from: ENC(5ZiHsLrR86Uq2PqGAQIYV6jkNA/accY+EMEEQO2w3po=)
  password: ENC(0AazeTbYUql51UoRje1W2wZc/gDvQX2s)

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
